# Generated by Django 4.2.16 on 2025-08-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('action_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('active_users', models.IntegerField()),
                ('properties_listed', models.IntegerField()),
                ('ai_conversations', models.IntegerField()),
                ('total_deals', models.IntegerField()),
                ('monthly_profit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('voice_calls_count', models.IntegerField()),
                ('report_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('audit_trail', models.TextField()),
                ('system_health', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=50)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('record_date', models.DateField()),
            ],
        ),
    ]
