# Generated by Django 4.2.16 on 2025-08-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deelflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmetrics',
            name='ai_conversations',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
