# Generated by Django 4.2.16 on 2025-09-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deelflow', '0003_organization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1992, max_length=255),
            preserve_default=False,
        ),
    ]
