# Generated by Django 4.2.23 on 2025-09-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deelflow', '0005_permission_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('ai_confidence', models.FloatField()),
                ('distress_level', models.FloatField()),
                ('motivation', models.CharField(max_length=255)),
                ('timeline', models.CharField(max_length=255)),
                ('roi_percent', models.FloatField()),
                ('cap_rate', models.FloatField()),
                ('cash_flow', models.FloatField()),
                ('market_stability_score', models.FloatField()),
                ('comparables_confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
