# Generated by Django 4.2.23 on 2025-09-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deelflow', '0009_campaign_campaignperformance_campaignpropertystats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(choices=[('public_record', 'Public Record'), ('property_site', 'Property Site'), ('social_media', 'Social Media'), ('court_record', 'Court Record'), ('mls', 'MLS')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('motivation_score', models.FloatField(default=0.0)),
                ('property_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('financial_situation', models.CharField(blank=True, max_length=100, null=True)),
                ('timeline_urgency', models.CharField(blank=True, max_length=100, null=True)),
                ('negotiation_style', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
