# Generated by Django 4.2.23 on 2025-09-15 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deelflow', '0010_discoveredlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('voice', 'Voice'), ('social', 'Social Media'), ('mail', 'Direct Mail')], max_length=20)),
                ('message_template', models.TextField()),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('response', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='deelflow.outreachcampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deelflow.discoveredlead')),
            ],
        ),
    ]
