# Generated by Django 4.2.16 on 2025-09-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deelflow', '0011_outreachcampaign_campaignrecipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='start_date',
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(default='new', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('call', 'Call')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='distress_indicators',
            field=models.CharField(blank=True, default='[]', max_length=500),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='geographic_scope_type',
            field=models.CharField(choices=[('zip', 'Zip'), ('county', 'County'), ('state', 'State')], default='zip', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='geographic_scope_values',
            field=models.CharField(blank=True, default='[]', max_length=500),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='minimum_equity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subject_line',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='use_ai_personalization',
            field=models.BooleanField(default=False),
        ),
    ]
