# Generated by Django 4.2.16 on 2025-10-18 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deelflow', '0015_campaign_age_range_campaign_buyer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
