# Generated by Django 4.2.16 on 2025-10-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deelflow', '0017_property_arv_property_assignment_fee_property_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
