# Generated by Django 4.2.16 on 2025-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deelflow', '0018_alter_campaign_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='channel',
            field=models.CharField(blank=True, default='[]', max_length=500),
        ),
    ]
