# Generated by Django 4.2.16 on 2025-10-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deelflow', '0020_auto_20251021_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_gateway', models.CharField(choices=[('stripe', 'Stripe'), ('paytm', 'Paytm'), ('razorpay', 'Razorpay'), ('paypal', 'PayPal')], default='stripe', max_length=50)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='deelflow.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='deelflow_pa_user_id_48b9db_idx'), models.Index(fields=['status'], name='deelflow_pa_status_a67387_idx'), models.Index(fields=['transaction_id'], name='deelflow_pa_transac_87160e_idx')],
            },
        ),
    ]
